/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopwheels;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felipe
 */
public class AlteraProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlteraProduto
     */
    public AlteraProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescricao = new javax.swing.JTextArea();
        txtCategoria = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar Produto");
        setMaximumSize(new java.awt.Dimension(658, 550));
        setMinimumSize(new java.awt.Dimension(658, 550));
        setPreferredSize(new java.awt.Dimension(658, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade em estoque :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria :");

        txtNome.setBackground(new java.awt.Color(153, 153, 153));

        txtaDescricao.setBackground(new java.awt.Color(153, 153, 153));
        txtaDescricao.setColumns(20);
        txtaDescricao.setLineWrap(true);
        txtaDescricao.setRows(5);
        jScrollPane1.setViewportView(txtaDescricao);

        txtCategoria.setBackground(new java.awt.Color(153, 153, 153));

        txtQuantidade.setBackground(new java.awt.Color(153, 153, 153));

        txtValor.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID :");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 220);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProduto.setOpaque(false);
        jScrollPane2.setViewportView(tblProduto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 310, 630, 200);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        jPanel6.setOpaque(false);

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(153, 153, 153));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(153, 153, 153));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(210, 220, 411, 82);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backGrounds/AlterarProduto.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 647, 532);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        // Atualizar tabela(tblFuncionario)
            atualizarTabela();
        
        // Desabilitar campos para edição
            desabilitar();
            
        // Limpar campos
            limpar();
            
        // Desabilitar botões
            btnSalvar.setEnabled(false);
            btnCancelar.setEnabled(false);
            
    }//GEN-LAST:event_formComponentShown

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        // Pegando dados da tabela
            if (tblProduto.getRowCount() > 0) {
                int linhaSelecionada =tblProduto.getSelectedRow();
            
            // Guardando valores pegos
                String id = tblProduto.getValueAt(linhaSelecionada, 0).toString();
                String nome = tblProduto.getValueAt(linhaSelecionada, 1).toString();
                String categoria = tblProduto.getValueAt(linhaSelecionada, 2).toString();
                String valor = tblProduto.getValueAt(linhaSelecionada, 3).toString();
                String quantidade = tblProduto.getValueAt(linhaSelecionada, 4).toString();
                String descricao = tblProduto.getValueAt(linhaSelecionada, 5).toString();
            
                
            // Colocando informações nos campos    
                txtID.setText(id);
                txtNome.setText(nome);
                txtCategoria.setText(categoria);
                txtValor.setText(valor);
                txtQuantidade.setText(quantidade);
                txtaDescricao.setText(descricao);
            
            // Habilitar campos para editar   
                habilitar();
                
            // Habilitar botões
                btnCancelar.setEnabled(true);
                btnSalvar.setEnabled(true);
            
            // Desabilitar botões
                btnExcluir.setEnabled(false);
                btnAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        // Limpar campos
            limpar();
        
        // Desabilitar campos para edição
            desabilitar();
        
        // Desabilitar botões
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
            
        // Habilitar botões
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        if (tblProduto.getRowCount() > 0) {
            
        // Setando valores nas variáveis    
            if (JOptionPane.showConfirmDialog(null, "Ao excluir um produto, dados de itens vendidos referentes a ele serão excluidos \nDeseja realmente excluir ?")== JOptionPane.OK_OPTION) {
                int linhaSelecionada = tblProduto.getSelectedRow();
                String id = tblProduto.getValueAt(linhaSelecionada, 0).toString();
            
        // Conectando no Banco        
            try {
                Connection conexaoDB = ConexaoDB.abrir();
            
            // Executando comando MySQL para excluir itens vendidos   
                CallableStatement comandoExIte = conexaoDB.prepareCall("DELETE FROM itensVend WHERE ite_fk_produto=?");
                comandoExIte.setString(1, id);
                comandoExIte.execute();    
                
            // Executando comando MySQL para excluir produto   
                CallableStatement comandoEx = conexaoDB.prepareCall("DELETE FROM produto WHERE pro_id=?");
                comandoEx.setInt(1, Integer.parseInt(id));
                comandoEx.execute();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Botao excluir " +e.getMessage());
            
            }
            
        }
        }
        
        // Atualizar tabela
            atualizarTabela();
         
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        // Declarando variáveis
            String id = txtID.getText();
            String nome = txtNome.getText();
            String categoria = txtCategoria.getText();
            String valor = txtValor.getText();
            String quantidade = txtQuantidade.getText();
            String descricao = txtaDescricao.getText();
        
            
        // Salvando na tabela do BD
            if (!"".equals(nome) && !"".equals(nome) && !"".equals(categoria) && !"".equals(valor) && !"".equals(quantidade) && !"".equals(descricao)){
        
        // Conectando no banco    
            try {
                Connection conexao = ConexaoDB.abrir();
            
            // Executando comando MySQL
                CallableStatement comandoPro = conexao.prepareCall("UPDATE produto SET pro_nome=?, pro_categoria=?, pro_valor=?, pro_qtd_est=?, pro_descricao=? WHERE pro_id=?");
                comandoPro.setString(1, nome);
                comandoPro.setString(2, categoria);
                comandoPro.setString(3, valor);
                comandoPro.setString(4, quantidade);
                comandoPro.setString(5, descricao);
                comandoPro.setString(6, id);
                comandoPro.execute();
                
                JOptionPane.showMessageDialog(null, "Alterado com sucesso");
        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Botão salvar" + e.getMessage());
            
            }
            }else{
                JOptionPane.showMessageDialog(null, "Prencha todos os campos!");   
            }
        
    // Limpar campos    
        limpar();
    
    // Desabilitar campos
        desabilitar();
    
    // Desabilitar botões
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    
    // Habilitar botões
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    
    // Atualizar tabela
        atualizarTabela();
        
    }//GEN-LAST:event_btnSalvarActionPerformed



public void atualizarTabela(){
    
// Definindo modelo da tabela
    DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("VALOR");
        modelo.addColumn("QUANTIDADE EM ESTOQUE");
        modelo.addColumn("DESCRIÇÃO");
        tblProduto.setModel(modelo);
       
    // Conectando com o DB
        try {
            Connection conexaoDB = ConexaoDB.abrir();
            Statement comandoPRO = conexaoDB.createStatement();
            ResultSet resultadoTbl = comandoPRO.executeQuery("SELECT * FROM produto");
        
        // Setando valores nas linhas da tabela    
            while (resultadoTbl.next()) {
                Object[] linha = new Object[6];
                linha[0] = resultadoTbl.getInt("pro_id");
                linha[1] = resultadoTbl.getString("pro_nome");
                linha[2] = resultadoTbl.getString("pro_categoria");
                linha[3] = resultadoTbl.getString("pro_valor");
                linha[4] = resultadoTbl.getString("pro_qtd_est");
                linha[5] = resultadoTbl.getString("pro_descricao");
                modelo.insertRow(tblProduto.getRowCount(), linha);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Atualizar tabela" +e.getMessage());
        }  
        
}    


public void desabilitar(){
  
// Desabilitar campos para edições
    txtNome.setEditable(false);
    txtCategoria.setEditable(false);
    txtValor.setEditable(false);
    txtQuantidade.setEditable(false);
    txtaDescricao.setEditable(false);
    
}


public void habilitar(){
 
// Habilitar campos para edições
    txtNome.setEditable(true);
    txtCategoria.setEditable(true);
    txtValor.setEditable(true);
    txtQuantidade.setEditable(true);
    txtaDescricao.setEditable(true);
    
}


public void limpar(){
// Limpar campos
    txtID.setText("");
    txtNome.setText("");
    txtCategoria.setText("");
    txtValor.setText("");
    txtQuantidade.setText("");
    txtaDescricao.setText("");  
    
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextArea txtaDescricao;
    // End of variables declaration//GEN-END:variables
}
