/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopwheels;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felipe
 */
public class AlteraLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlteraLogin
     */
    public AlteraLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbFuncionario = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogin = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar Login");
        setMaximumSize(new java.awt.Dimension(388, 496));
        setMinimumSize(new java.awt.Dimension(388, 496));
        setPreferredSize(new java.awt.Dimension(388, 496));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel2.setOpaque(false);

        txtLogin.setBackground(new java.awt.Color(111, 0, 0));
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("* Máximo 8 caracteres");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Funcionário :");

        cmbFuncionario.setBackground(new java.awt.Color(111, 0, 0));
        cmbFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        cmbFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID :");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(111, 0, 0));
        txtID.setForeground(new java.awt.Color(255, 255, 255));

        txtSenha.setBackground(new java.awt.Color(111, 0, 0));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenha))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 6, 358, 200);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel4.setOpaque(false);

        btnSalvar.setBackground(new java.awt.Color(102, 102, 102));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(102, 102, 102));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(102, 102, 102));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnSalvar});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnCancelar))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(6, 213, 364, 116);

        tblLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLogin);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(7, 334, 363, 127);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backGrounds/AlteraLogin.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 380, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        // Colocando valores no ComboBox
            
        // Conectando no Banco    
            try {
                Connection conexao = ConexaoDB.abrir();
                
            // Executando comando MySQL
                Statement comando = conexao.createStatement();
                ResultSet resultado = comando.executeQuery("SELECT fun_id, fun_nome FROM funcionario ORDER BY fun_nome");
            
            // Inserindo itens    
                while (resultado.next()) {
                    int id = resultado.getInt("fun_id");
                    String nome = resultado.getString("fun_nome");
                    cmbFuncionario.addItem(id + "-" + nome);
                }
            
            } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Combo Component Show " +e.getMessage());
        }
            
        // Atualizar tabela
            atualizarTabela();
         
        // Desabilitar campos
            desabilitar();
            
        // Desabilitar botões
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
               
    }//GEN-LAST:event_formComponentShown

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        // Pegando dados da tabela
            if (tblLogin.getRowCount() > 0) {
                int linhaSelecionada = tblLogin.getSelectedRow();
            
            // Guardando valores pegos
                String id = tblLogin.getValueAt(linhaSelecionada, 0).toString();
                String login = tblLogin.getValueAt(linhaSelecionada, 1).toString();
                String senha = tblLogin.getValueAt(linhaSelecionada, 2).toString();
                String funcionario = tblLogin.getValueAt(linhaSelecionada, 3).toString();
                
            // Pegando id do funcionario    
            // Conectando no Banco
                try {
                    Connection conexao = ConexaoDB.abrir();
                    
                // Executando comando MySQL    
                    Statement comando = conexao.createStatement();
                    ResultSet resultado = comando.executeQuery("SELECT fun_id, fun_nome FROM funcionario ORDER BY fun_nome");
                
                // Colocando resultado em variáveis    
                    while (resultado.next()) {
                        int idFun = resultado.getInt("fun_id");
                        String nome = resultado.getString("fun_nome");
                
                // Verificando igualdade entre resultados        
                    if (nome.equals(funcionario)) {
                        String nomeCli;
                        nomeCli = (idFun + "-" + funcionario) ;
                
                    // Colocando item na Combo Box    
                        cmbFuncionario.setSelectedItem(nomeCli);
                        
                    }
                }
            
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Botão Alterar " +e.getMessage());
                }

            // Colocando informações nos campos    
                txtID.setText(id);
                txtLogin.setText(login);
                txtSenha.setText(senha);
                
            // Habilitar campos para editar   
                habilitar();
                
            // Habilitar botões
                btnCancelar.setEnabled(true);
                btnSalvar.setEnabled(true);
            
            // Desabilitar botões
                btnExcluir.setEnabled(false);
                btnAlterar.setEnabled(false);
        
        }
                             
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        if (tblLogin.getRowCount() > 0) {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir")== JOptionPane.OK_OPTION) {
                int linhaSelecionada = tblLogin.getSelectedRow();
                String id = tblLogin.getValueAt(linhaSelecionada, 0).toString();
            
        // Conectando no Banco        
            try {
                Connection conexao = ConexaoDB.abrir();
                
            // Executando comando MySQL    
                CallableStatement comando = conexao.prepareCall("DELETE FROM login WHERE log_id=?");
                comando.setInt(1, Integer.parseInt(id));
                comando.execute();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Botao excluir " +e.getMessage());
            
            }
            
        }
        }
        
        // Atualizar tabela
            atualizarTabela();
         
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        // Declarando variáveis
            String id = txtID.getText();
            String login = txtLogin.getText();
            String senha = txtSenha.getText();
            String funcionario = cmbFuncionario.getSelectedItem().toString();
        
        // Pegando id do cliente    
            String[] pegaIDFun = funcionario.split("-");
            int idFun = Integer.parseInt(pegaIDFun[0]);
            
        
        // Salvando na tabela do BD
            if (!"".equals(login) && !"".equals(senha)){
        
        // Conectando no banco    
            try {
                Connection conexao = ConexaoDB.abrir();
            
            // Executando comando MySQL
                CallableStatement comandoLog = conexao.prepareCall("UPDATE login SET log_login=?, log_senha=?, log_fk_funcionario=? WHERE log_id=?");
                comandoLog.setString(1, login);
                comandoLog.setString(2, senha);
                comandoLog.setInt(3, idFun);
                comandoLog.setString(4, id);
                comandoLog.execute();
                
                JOptionPane.showMessageDialog(null, "Alterado com sucesso");
        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Botão salvar" + e.getMessage());
            
            }
            }else{
                JOptionPane.showMessageDialog(null, "Prencha todos os campos!");   
            }
        
    // Limpar campos    
        limpar();
    
    // Desabilitar campos
        desabilitar();
    
    // Desabilitar botões
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    
    // Habilitar botões
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    
    // Atualizar tabela
        atualizarTabela();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        // Limpar campos
            limpar();
        
        // Desabilitar campos para edição
            desabilitar();
        
        // Desabilitar botões
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
            
        // Habilitar botões
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            
    }//GEN-LAST:event_btnCancelarActionPerformed


    
public void atualizarTabela(){
    
    // Definindo modelo da tabela
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("LOGIN");
        modelo.addColumn("SENHA");
        modelo.addColumn("FUNCIONÁRIO");
        tblLogin.setModel(modelo);
       
    // Conectando com o DB
        try {
            Connection conexaoDB = ConexaoDB.abrir();
        
        // Executando comando MySQL    
            Statement comandoFun = conexaoDB.createStatement();
            ResultSet resultadoTbl = comandoFun.executeQuery("SELECT log_id, fun_nome, log_login, log_senha FROM login INNER JOIN funcionario ON log_fk_funcionario=fun_id");
        
        // Setando valores nas linhas da tabela    
            while (resultadoTbl.next()) {
                Object[] linha = new Object[4];
                linha[0] = resultadoTbl.getInt("log_id");
                linha[1] = resultadoTbl.getString("log_login");
                linha[2] = resultadoTbl.getString("log_senha");
                linha[3] = resultadoTbl.getString("fun_nome");
                modelo.insertRow(tblLogin.getRowCount(), linha);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Atualizar tabela" +e.getMessage());
        } 
        
}    


public void desabilitar(){
  // Desabilitar campos para edições
      txtLogin.setEditable(false);
      txtSenha.setEditable(false);
      cmbFuncionario.setEnabled(false);
      
}


public void habilitar(){
  // Habilitar campos para edições
      txtLogin.setEditable(true);
      txtSenha.setEditable(true);
      cmbFuncionario.setEnabled(true);
      
}


public void limpar(){
  // Limpar campos  
      txtID.setText("");
      txtLogin.setText("");
      txtSenha.setText("");
      cmbFuncionario.setSelectedIndex(0);
      
}  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLogin;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
