/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopwheels;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felipe
 */
public class AlteraFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlteraFuncionario
     */
    public AlteraFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        cmbDiaNasc = new javax.swing.JComboBox();
        cmbMesNasc = new javax.swing.JComboBox();
        cmbAnoNasc = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtIDFun = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNumResid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ftxtCep = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        cmbDiaAdm = new javax.swing.JComboBox();
        cmbMesAdm = new javax.swing.JComboBox();
        cmbAnoAdm = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCTPS = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alterar Funcionário");
        setMaximumSize(new java.awt.Dimension(984, 570));
        setMinimumSize(new java.awt.Dimension(984, 570));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(984, 570));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data de nascimento :");

        txtNomeFun.setBackground(new java.awt.Color(105, 190, 184));
        txtNomeFun.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cmbDiaNasc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDiaNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbMesNasc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cmbMesNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbAnoNasc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        cmbAnoNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ID :");

        txtIDFun.setEditable(false);
        txtIDFun.setBackground(new java.awt.Color(105, 190, 184));
        txtIDFun.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDFun, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeFun))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtIDFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 490, 172);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel3.setOpaque(false);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Logradouro :");

        txtLogradouro.setBackground(new java.awt.Color(105, 190, 184));
        txtLogradouro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Número residencial :");

        txtNumResid.setBackground(new java.awt.Color(105, 190, 184));
        txtNumResid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bairro :");

        txtBairro.setBackground(new java.awt.Color(105, 190, 184));
        txtBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cidade :");

        txtCidade.setBackground(new java.awt.Color(105, 190, 184));
        txtCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CEP :");

        ftxtCep.setBackground(new java.awt.Color(105, 190, 184));
        try {
            ftxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLogradouro))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumResid, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 191, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNumResid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(512, 6, 450, 242);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Trabalhistas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel2.setOpaque(false);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cargo :");

        txtCargo.setBackground(new java.awt.Color(105, 190, 184));
        txtCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cmbDiaAdm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDiaAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbMesAdm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cmbMesAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbAnoAdm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        cmbAnoAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data de admissão :");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CTPS :");

        txtCTPS.setBackground(new java.awt.Color(105, 190, 184));
        txtCTPS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDiaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMesAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAnoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbDiaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMesAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 180, 490, 172);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel4.setOpaque(false);

        btnSalvar.setBackground(new java.awt.Color(204, 160, 0));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 160, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(204, 160, 0));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(204, 160, 0));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(518, 260, 450, 88);

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblFuncionario.setOpaque(false);
        jScrollPane1.setViewportView(tblFuncionario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 354, 962, 178);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backGrounds/AlterarFuncionario.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.setMaximumSize(new java.awt.Dimension(974, 538));
        jLabel18.setMinimumSize(new java.awt.Dimension(974, 538));
        jLabel18.setName(""); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(974, 538));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 974, 538);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        // Atualizar tabela(tblFuncionario)
            atualizarTabela();
        
        // Desabilitar campos para edição
            desabilitar();
            
        // Limpar campos
            limpar();
            
        // Desabilitar botões
            btnSalvar.setEnabled(false);
            btnCancelar.setEnabled(false);
            
    }//GEN-LAST:event_formComponentShown

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        // Pegando dados da tabela
            if (tblFuncionario.getRowCount() > 0) {
                int linhaSelecionada = tblFuncionario.getSelectedRow();
            
            // Informações Pessoais
                String id = tblFuncionario.getValueAt(linhaSelecionada, 0).toString();
                String nome = tblFuncionario.getValueAt(linhaSelecionada, 1).toString();
                String dataNasc = tblFuncionario.getValueAt(linhaSelecionada, 2).toString();
             
               // Separando data 
                 String[] pegaDataNasc = dataNasc.split("-");
                 String diaNasc = (pegaDataNasc[2]);
                 String mesNasc = (pegaDataNasc[1]);
                 String anoNasc = (pegaDataNasc[0]);
                
                
            // Informações trabalhistas    
                String cargo = tblFuncionario.getValueAt(linhaSelecionada, 3).toString();
                String dataAdm = tblFuncionario.getValueAt(linhaSelecionada, 4).toString();
                
               // Separando data 
                 String[] pegaDataAdm = dataAdm.split("-");
                 String diaAdm = (pegaDataAdm[2]);
                 String mesAdm = (pegaDataAdm[1]);
                 String anoAdm = (pegaDataAdm[0]);
                
                String ctps = tblFuncionario.getValueAt(linhaSelecionada, 5).toString();
                
                
            // Informações de endereço    
                String logradouro = tblFuncionario.getValueAt(linhaSelecionada, 6).toString();
                String bairro = tblFuncionario.getValueAt(linhaSelecionada, 7).toString();
                String numResid = tblFuncionario.getValueAt(linhaSelecionada, 8).toString();
                String cidade = tblFuncionario.getValueAt(linhaSelecionada, 9).toString();
                String cep = tblFuncionario.getValueAt(linhaSelecionada, 10).toString();
                
                
            // Colocando informações nos campos    
                txtIDFun.setText(id);
                txtNomeFun.setText(nome);
                cmbDiaNasc.setSelectedItem(diaNasc);
                cmbMesNasc.setSelectedItem(mesNasc);
                cmbAnoNasc.setSelectedItem(anoNasc);
                
                txtCargo.setText(cargo);
                cmbDiaAdm.setSelectedItem(diaAdm);
                cmbMesAdm.setSelectedItem(mesAdm);
                cmbAnoAdm.setSelectedItem(anoAdm);
                txtCTPS.setText(ctps);
                
                txtLogradouro.setText(logradouro);
                txtBairro.setText(bairro);
                txtNumResid.setText(numResid);
                txtCidade.setText(cidade);
                ftxtCep.setText(cep);
            
            // Habilitar campos para editar   
                habilitar();
                
            // Habilitar botões
                btnCancelar.setEnabled(true);
                btnSalvar.setEnabled(true);
            
            // Desabilitar botões
                btnExcluir.setEnabled(false);
                btnAlterar.setEnabled(false);
        }
            
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        // Limpar campos
            limpar();
        
        // Desabilitar campos para edição
            desabilitar();
        
        // Desabilitar botões
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
            
        // Habilitar botões
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);  
            
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        // Declarando variáveis
        // Informações pessoais
            String id = txtIDFun.getText();
            String nome = txtNomeFun.getText();
            String diaNasc = cmbDiaNasc.getSelectedItem().toString();
            String mesNasc = cmbMesNasc.getSelectedItem().toString();
            String anoNasc = cmbAnoNasc.getSelectedItem().toString();
        
            Date dataNasc = Date.valueOf(anoNasc + "-" + mesNasc + "-" + diaNasc);
        
        // Informações endereco
            String logradouro = txtLogradouro.getText();
            String bairro = txtBairro.getText();
            String numResid = txtNumResid.getText();
            String cidade = txtCidade.getText();
            String cep = ftxtCep.getText();
        
                
        // Informações trabalhistas
            String cargo = txtCargo.getText();
            String diaAdm = cmbDiaAdm.getSelectedItem().toString();
            String mesAdm = cmbMesAdm.getSelectedItem().toString();
            String anoAdm = cmbAnoAdm.getSelectedItem().toString();
            String ctps = txtCTPS.getText();
        
            Date dataAdm = Date.valueOf(anoAdm + "-" + mesAdm + "-" + diaAdm);
        
        // Salvando na tabela do BD
            if (!"".equals(nome) && !"".equals(logradouro) && !"".equals(bairro) && !"".equals(numResid) && !"".equals(cidade) && !"".equals(cep) && !"".equals(cargo) && !"".equals(ctps)){
        
        // Conectando no banco    
            try {
                Connection conexao = ConexaoDB.abrir();
            
            // Executando comando MySQL
                CallableStatement comandoFun = conexao.prepareCall("UPDATE funcionario SET fun_nome=?, fun_data_nasc=?, fun_logradouro=?, fun_bairro=?, fun_cidade=?, fun_num_resid=?, fun_cep=?, fun_cargo=?, fun_data_adm=?, fun_ctps=? WHERE fun_id=?");
                comandoFun.setString(1, nome);
                comandoFun.setDate(2, dataNasc);
                comandoFun.setString(3, logradouro);
                comandoFun.setString(4, bairro);
                comandoFun.setString(5, cidade);
                comandoFun.setString(6, numResid);
                comandoFun.setString(7, cep);
                comandoFun.setString(8, cargo);
                comandoFun.setDate(9, dataAdm);
                comandoFun.setString(10, ctps);
                comandoFun.setString(11, id);
                comandoFun.execute();
                
                JOptionPane.showMessageDialog(null, "Alterado com sucesso");
        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Botão salvar" + e.getMessage());
            
            }
            }else{
                JOptionPane.showMessageDialog(null, "Prencha todos os campos!");   
            }
        
    // Limpar campos    
        limpar();
    
    // Desabilitar campos
        desabilitar();
    
    // Desabilitar botões
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    
    // Habilitar botões
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    
    // Atualizar tabela
        atualizarTabela();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        if (tblFuncionario.getRowCount() > 0) {
         if (JOptionPane.showConfirmDialog(null, "Ao excluir um(a) funcionário(a), dados de vendas e entregas realizadas por ele(a) serão excluidos \nDeseja realmente excluir ?")== JOptionPane.OK_OPTION) {   
        
        // Setando valores nas variáveis    
            int linhaSelecionada = tblFuncionario.getSelectedRow();
            String id = tblFuncionario.getValueAt(linhaSelecionada, 0).toString();
            
            // Conectando no Banco        
                try {
                    Connection conexaoDB = ConexaoDB.abrir();
                
                // Pegando id de vendas relacionadas ao carro para excluir itens vendidos
                            Statement comandoIdVen = conexaoDB.createStatement();
                            ResultSet resultadoIdVen = comandoIdVen.executeQuery("SELECT ven_id FROM venda WHERE ven_fk_funcionario="+id);
                            
                            while (resultadoIdVen.next()) {
                                int idVen = resultadoIdVen.getInt("ven_id");
                                
                             // Executando comando MySQL para excluir itens vendidos   
                                 CallableStatement comandoExIte = conexaoDB.prepareCall("DELETE FROM itensVend WHERE ite_fk_venda=?");
                                 comandoExIte.setInt(1, idVen);
                                 comandoExIte.execute();
                         
                            }    
                    
                // Executando comando MySQL para excluir venda   
                    CallableStatement comandoExVen = conexaoDB.prepareCall("DELETE FROM venda WHERE ven_fk_funcionario=?");
                    comandoExVen.setInt(1, Integer.parseInt(id));
                    comandoExVen.execute();
                
                // Executando comando MySQL para excluir entrega   
                    CallableStatement comandoExEnt = conexaoDB.prepareCall("DELETE FROM entrega WHERE ent_fk_funcionario=?");
                    comandoExEnt.setInt(1, Integer.parseInt(id));
                    comandoExEnt.execute();
                
                // Executando comando MySQL para excluir login   
                    CallableStatement comandoExLog = conexaoDB.prepareCall("DELETE FROM login WHERE log_fk_funcionario=?");
                    comandoExLog.setInt(1, Integer.parseInt(id));
                    comandoExLog.execute();
                
                // Executando comando MySQL para excluir funcionario   
                    CallableStatement comandoExFun = conexaoDB.prepareCall("DELETE FROM funcionario WHERE fun_id=?");
                    comandoExFun.setInt(1, Integer.parseInt(id));
                    comandoExFun.execute();
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Botao excluir " +e.getMessage());
            
                }
            
            
         }
        }
        
        // Atualizar tabela
            atualizarTabela();
         
    }//GEN-LAST:event_btnExcluirActionPerformed

    
public void atualizarTabela(){
    
// Definindo modelo da tabela
    DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("DATA DE NASCIMENTO");
        modelo.addColumn("CARGO");
        modelo.addColumn("DATA DE ADMISSÃO");
        modelo.addColumn("CTPS");
        modelo.addColumn("LOGRADOURO");
        modelo.addColumn("BAIRRO");
        modelo.addColumn("NUMERO RESIDENCIAL");
        modelo.addColumn("CIDADE");
        modelo.addColumn("CEP");
        tblFuncionario.setModel(modelo);
       
    // Conectando com o DB
        try {
            Connection conexaoDB = ConexaoDB.abrir();
            Statement comandoFun = conexaoDB.createStatement();
            ResultSet resultadoTbl = comandoFun.executeQuery("SELECT * FROM funcionario WHERE fun_id > 1");
        
        // Setando valores nas linhas da tabela    
            while (resultadoTbl.next()) {
                Object[] linha = new Object[11];
                linha[0] = resultadoTbl.getInt("fun_id");
                linha[1] = resultadoTbl.getString("fun_nome");
                linha[2] = resultadoTbl.getString("fun_data_nasc");
                linha[3] = resultadoTbl.getString("fun_cargo");
                linha[4] = resultadoTbl.getString("fun_data_adm");
                linha[5] = resultadoTbl.getString("fun_ctps");
                linha[6] = resultadoTbl.getString("fun_logradouro");
                linha[7] = resultadoTbl.getString("fun_bairro");
                linha[8] = resultadoTbl.getString("fun_num_resid");
                linha[9] = resultadoTbl.getString("fun_cidade");
                linha[10] = resultadoTbl.getString("fun_cep");
                modelo.insertRow(tblFuncionario.getRowCount(), linha);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Atualizar tabela" +e.getMessage());
        }  
        
}    


public void desabilitar(){
  
// Desabilitar campos para edições
    txtNomeFun.setEditable(false);
    cmbDiaNasc.setEnabled(false);
    cmbMesNasc.setEnabled(false);
    cmbAnoNasc.setEnabled(false);
    txtLogradouro.setEditable(false);
    txtBairro.setEditable(false);
    txtNumResid.setEditable(false);
    txtCidade.setEditable(false);
    ftxtCep.setEditable(false);
    txtCargo.setEditable(false);
    txtCTPS.setEditable(false);
    cmbDiaAdm.setEnabled(false);
    cmbMesAdm.setEnabled(false);
    cmbAnoAdm.setEnabled(false);
    
}


public void habilitar(){
 
// Habilitar campos para edições
    txtNomeFun.setEditable(true);
    cmbDiaNasc.setEnabled(true);
    cmbMesNasc.setEnabled(true);
    cmbAnoNasc.setEnabled(true);
    txtLogradouro.setEditable(true);
    txtBairro.setEditable(true);
    txtNumResid.setEditable(true);
    txtCidade.setEditable(true);
    ftxtCep.setEditable(true);
    txtCargo.setEditable(true);
    txtCTPS.setEditable(true);
    cmbDiaAdm.setEnabled(true);
    cmbMesAdm.setEnabled(true);
    cmbAnoAdm.setEnabled(true);
    
}


public void limpar(){
// Limpar campos  
    txtIDFun.setText("");
    txtNomeFun.setText("");
    cmbDiaNasc.setSelectedIndex(0);
    cmbMesNasc.setSelectedIndex(0);
    cmbAnoNasc.setSelectedIndex(0);
    txtLogradouro.setText("");
    txtBairro.setText("");
    txtNumResid.setText("");
    txtCidade.setText("");
    ftxtCep.setText("");
    txtCargo.setText("");
    txtCTPS.setText("");
    cmbDiaAdm.setSelectedIndex(0);
    cmbMesAdm.setSelectedIndex(0);
    cmbAnoAdm.setSelectedIndex(0);  
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbAnoAdm;
    private javax.swing.JComboBox cmbAnoNasc;
    private javax.swing.JComboBox cmbDiaAdm;
    private javax.swing.JComboBox cmbDiaNasc;
    private javax.swing.JComboBox cmbMesAdm;
    private javax.swing.JComboBox cmbMesNasc;
    private javax.swing.JFormattedTextField ftxtCep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCTPS;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtIDFun;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JTextField txtNumResid;
    // End of variables declaration//GEN-END:variables
}
