/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopwheels;

import java.awt.*;
import java.sql.*;
import java.text.NumberFormat;
import javax.swing.*;

/**
 *
 * @author felipe
 */
public class TelaPrincipalADM extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    // variável usada como fundo
    
    public TelaPrincipalADM() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        panelTelaPrincipal = new javax.swing.JDesktopPane();
        txtCaixa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnIniciarVenda1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuCadastrarFun = new javax.swing.JMenuItem();
        menuAlterarFun = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCadastrarTel = new javax.swing.JMenuItem();
        menuAlterarTel = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuCadastrarCli = new javax.swing.JMenuItem();
        menuAlterarCli = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuCadastrarCar = new javax.swing.JMenuItem();
        menuAlterarCar = new javax.swing.JMenuItem();
        jmenu = new javax.swing.JMenu();
        menuCadastrarPdt = new javax.swing.JMenuItem();
        menuAlterarPdt = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuCadastrarLogin = new javax.swing.JMenuItem();
        menuAlterarLogin = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuIniciarVenda = new javax.swing.JMenuItem();
        menuCancelarVenda = new javax.swing.JMenuItem();
        menuRegVenda = new javax.swing.JMenuItem();
        menuPMV = new javax.swing.JMenuItem();
        menuPesquisaPdt = new javax.swing.JMenuItem();
        menuFMV = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuCadastrarEntrega = new javax.swing.JMenuItem();
        menuPendente = new javax.swing.JMenuItem();
        menuFinalizada = new javax.swing.JMenuItem();
        mnu = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShopWheels");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelTelaPrincipal.setPreferredSize(new java.awt.Dimension(1427, 854));

        txtCaixa.setEditable(false);
        txtCaixa.setBackground(new java.awt.Color(153, 153, 153));
        txtCaixa.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtCaixa.setMinimumSize(new java.awt.Dimension(5, 38));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Caixa :");

        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/calculadora.png"))); // NOI18N
        jButton1.setText("Calculadora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnIniciarVenda1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnIniciarVenda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/iniciarVenda.png"))); // NOI18N
        btnIniciarVenda1.setText("Iniciar Venda");
        btnIniciarVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarVenda1ActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/sair.png"))); // NOI18N
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        panelTelaPrincipal.setLayer(txtCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelTelaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelTelaPrincipal.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelTelaPrincipal.setLayer(btnIniciarVenda1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelTelaPrincipal.setLayer(btnSair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelTelaPrincipalLayout = new javax.swing.GroupLayout(panelTelaPrincipal);
        panelTelaPrincipal.setLayout(panelTelaPrincipalLayout);
        panelTelaPrincipalLayout.setHorizontalGroup(
            panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTelaPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIniciarVenda1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1020, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        panelTelaPrincipalLayout.setVerticalGroup(
            panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarVenda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 971, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        panelTelaPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnIniciarVenda1, jButton1});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 990;
        gridBagConstraints.ipady = 660;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panelTelaPrincipal, gridBagConstraints);

        jMenu1.setText("Cadastro");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/funcionario.png"))); // NOI18N
        jMenu4.setText("Funcionário");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuCadastrarFun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarFun.setText("Cadastrar");
        menuCadastrarFun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarFunActionPerformed(evt);
            }
        });
        jMenu4.add(menuCadastrarFun);

        menuAlterarFun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        menuAlterarFun.setText("Alterar");
        menuAlterarFun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlterarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarFunActionPerformed(evt);
            }
        });
        jMenu4.add(menuAlterarFun);

        jMenu1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/telefone.png"))); // NOI18N
        jMenu5.setText("Telefone");

        menuCadastrarTel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarTel.setText("Cadastrar");
        menuCadastrarTel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarTelActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadastrarTel);

        menuAlterarTel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        menuAlterarTel.setText("Alterar");
        menuAlterarTel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlterarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarTelActionPerformed(evt);
            }
        });
        jMenu5.add(menuAlterarTel);

        jMenu1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/cliente.png"))); // NOI18N
        jMenu7.setText("Cliente");

        menuCadastrarCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarCli.setText("Cadastrar");
        menuCadastrarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarCliActionPerformed(evt);
            }
        });
        jMenu7.add(menuCadastrarCli);

        menuAlterarCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.SHIFT_MASK));
        menuAlterarCli.setText("Alterar");
        menuAlterarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlterarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarCliActionPerformed(evt);
            }
        });
        jMenu7.add(menuAlterarCli);

        jMenu1.add(jMenu7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/carro.png"))); // NOI18N
        jMenu6.setText("Carro");

        menuCadastrarCar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarCar.setText("Cadastrar");
        menuCadastrarCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarCarActionPerformed(evt);
            }
        });
        jMenu6.add(menuCadastrarCar);

        menuAlterarCar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        menuAlterarCar.setText("Alterar");
        menuAlterarCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlterarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarCarActionPerformed(evt);
            }
        });
        jMenu6.add(menuAlterarCar);

        jMenu1.add(jMenu6);

        jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/produto.png"))); // NOI18N
        jmenu.setText("Produto");

        menuCadastrarPdt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarPdt.setText("Cadastrar");
        menuCadastrarPdt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarPdtActionPerformed(evt);
            }
        });
        jmenu.add(menuCadastrarPdt);

        menuAlterarPdt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.SHIFT_MASK));
        menuAlterarPdt.setText("Alterar");
        menuAlterarPdt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlterarPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarPdtActionPerformed(evt);
            }
        });
        jmenu.add(menuAlterarPdt);

        jMenu1.add(jmenu);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/login.png"))); // NOI18N
        jMenu9.setText("Login");

        menuCadastrarLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastrarLogin.setText("Cadastrar");
        menuCadastrarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarLoginActionPerformed(evt);
            }
        });
        jMenu9.add(menuCadastrarLogin);

        menuAlterarLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.SHIFT_MASK));
        menuAlterarLogin.setText("Alterar");
        menuAlterarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAlterarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarLoginActionPerformed(evt);
            }
        });
        jMenu9.add(menuAlterarLogin);

        jMenu1.add(jMenu9);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Venda");
        jMenu3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        menuIniciarVenda.setText("Iniciar venda");
        menuIniciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarVendaActionPerformed(evt);
            }
        });
        jMenu3.add(menuIniciarVenda);

        menuCancelarVenda.setText("Cancelar Venda");
        menuCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelarVendaActionPerformed(evt);
            }
        });
        jMenu3.add(menuCancelarVenda);

        menuRegVenda.setText("Registro de vendas");
        menuRegVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegVendaActionPerformed(evt);
            }
        });
        jMenu3.add(menuRegVenda);

        menuPMV.setText("Produtos mais vendidos");
        menuPMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPMVActionPerformed(evt);
            }
        });
        jMenu3.add(menuPMV);

        menuPesquisaPdt.setText("Consulta de produtos");
        menuPesquisaPdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaPdtActionPerformed(evt);
            }
        });
        jMenu3.add(menuPesquisaPdt);

        menuFMV.setText("Funcionário que mais vendeu");
        menuFMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFMVActionPerformed(evt);
            }
        });
        jMenu3.add(menuFMV);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Entrega");
        jMenu8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        menuCadastrarEntrega.setText("Cadastrar entrega");
        menuCadastrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarEntregaActionPerformed(evt);
            }
        });
        jMenu8.add(menuCadastrarEntrega);

        menuPendente.setText("Entregas pendentes");
        menuPendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPendenteActionPerformed(evt);
            }
        });
        jMenu8.add(menuPendente);

        menuFinalizada.setText("Entregas finalizadas");
        menuFinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFinalizadaActionPerformed(evt);
            }
        });
        jMenu8.add(menuFinalizada);

        jMenuBar1.add(jMenu8);

        mnu.setText("Sobre");
        mnu.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        mnu.add(menuSobre);

        jMenuBar1.add(mnu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void menuCadastrarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarFunActionPerformed
        // TODO add your handling code here:
        CadastraFuncionario abrir = new CadastraFuncionario();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarFunActionPerformed

    private void menuIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarVendaActionPerformed
        // TODO add your handling code here:
        Vender abrir = new Vender();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuIniciarVendaActionPerformed

    private void menuAlterarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarFunActionPerformed
        // TODO add your handling code here:
        AlteraFuncionario abrir = new AlteraFuncionario();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuAlterarFunActionPerformed

    private void menuCadastrarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarTelActionPerformed
        // TODO add your handling code here:
        CadastraTelefone abrir = new CadastraTelefone();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarTelActionPerformed

    private void menuAlterarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarTelActionPerformed
        // TODO add your handling code here:
        AlteraTelefone abrir = new AlteraTelefone();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuAlterarTelActionPerformed

    private void menuCadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarCliActionPerformed
        // TODO add your handling code here:
        CadastraCliente abrir = new CadastraCliente();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarCliActionPerformed

    private void menuCadastrarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarCarActionPerformed
        // TODO add your handling code here:
        CadastraCarro abrir = new CadastraCarro();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarCarActionPerformed

    private void menuAlterarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarCarActionPerformed
        // TODO add your handling code here:
        AlteraCarro abrir = new AlteraCarro();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuAlterarCarActionPerformed

    private void menuCadastrarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarPdtActionPerformed
        // TODO add your handling code here:
        CadastraProduto abrir = new CadastraProduto();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarPdtActionPerformed

    private void menuAlterarPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarPdtActionPerformed
        // TODO add your handling code here:
        AlteraProduto abrir = new AlteraProduto();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuAlterarPdtActionPerformed

    private void menuCadastrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarLoginActionPerformed
        // TODO add your handling code here:
        CadastraLogin abrir = new CadastraLogin();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarLoginActionPerformed

    private void menuAlterarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarLoginActionPerformed
        // TODO add your handling code here:
        AlteraLogin abrir = new AlteraLogin();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuAlterarLoginActionPerformed

    private void menuAlterarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarCliActionPerformed
        // TODO add your handling code here:
        AlteraCliente abrir = new AlteraCliente();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuAlterarCliActionPerformed

    private void menuCadastrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarEntregaActionPerformed
        // TODO add your handling code here:
        CadastraEntrega abrir = new CadastraEntrega();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCadastrarEntregaActionPerformed

    private void menuPendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPendenteActionPerformed
        // TODO add your handling code here:
        EntregasPendentes abrir = new EntregasPendentes();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuPendenteActionPerformed

    private void menuFinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFinalizadaActionPerformed
        // TODO add your handling code here:
        EntregasRealizadas abrir = new EntregasRealizadas();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuFinalizadaActionPerformed

    private void menuPesquisaPdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaPdtActionPerformed
        // TODO add your handling code here:
        PesquisaProduto abrir = new PesquisaProduto();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuPesquisaPdtActionPerformed

    private void menuRegVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegVendaActionPerformed
        // TODO add your handling code here:
        RegistroVenda abrir = new RegistroVenda();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuRegVendaActionPerformed

    private void menuCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelarVendaActionPerformed
        // TODO add your handling code here:
        CancelarVenda abrir = new CancelarVenda();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuCancelarVendaActionPerformed

    private void menuPMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPMVActionPerformed
        // TODO add your handling code here:
        ProdutosMaisVendidos abrir = new ProdutosMaisVendidos();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuPMVActionPerformed

    private void menuFMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFMVActionPerformed
        // TODO add your handling code here:
        FuncionarioQueMaisVendeu abrir = new FuncionarioQueMaisVendeu();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuFMVActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        // TODO add your handling code here:
        Sobre abrir = new Sobre();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_menuSobreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Calculadora abrir = new Calculadora();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIniciarVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarVenda1ActionPerformed
        // TODO add your handling code here:
        Vender abrir = new Vender();
        abrir.show();
        panelTelaPrincipal.add(abrir);
    }//GEN-LAST:event_btnIniciarVenda1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        TelaPrincipalADM.this.dispose();

        Login abrir = new Login();
        abrir.show();
    }//GEN-LAST:event_btnSairActionPerformed

// Abrir ocupando tela toda
public void setFullScreen(DisplayMode displayMode){
    GraphicsEnvironment environment = GraphicsEnvironment.getLocalGraphicsEnvironment();
    GraphicsDevice device = environment.getDefaultScreenDevice();
    final JFrame janela = new JFrame();
    janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    janela.setUndecorated(true);
    janela.setIgnoreRepaint(true);
    janela.setResizable(false);
    device.setFullScreenWindow(janela);
    
    if (displayMode != null && device.isDisplayChangeSupported()) {
            setDisplayMode(displayMode);
            // fix for mac os x
                janela.setSize(displayMode.getWidth(), displayMode.getHeight());
        }
        janela.createBufferStrategy(2);
        sleep(500);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarVenda1;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu jmenu;
    private javax.swing.JMenuItem menuAlterarCar;
    private javax.swing.JMenuItem menuAlterarCli;
    private javax.swing.JMenuItem menuAlterarFun;
    private javax.swing.JMenuItem menuAlterarLogin;
    private javax.swing.JMenuItem menuAlterarPdt;
    private javax.swing.JMenuItem menuAlterarTel;
    private javax.swing.JMenuItem menuCadastrarCar;
    private javax.swing.JMenuItem menuCadastrarCli;
    private javax.swing.JMenuItem menuCadastrarEntrega;
    private javax.swing.JMenuItem menuCadastrarFun;
    private javax.swing.JMenuItem menuCadastrarLogin;
    private javax.swing.JMenuItem menuCadastrarPdt;
    private javax.swing.JMenuItem menuCadastrarTel;
    private javax.swing.JMenuItem menuCancelarVenda;
    private javax.swing.JMenuItem menuFMV;
    private javax.swing.JMenuItem menuFinalizada;
    private javax.swing.JMenuItem menuIniciarVenda;
    private javax.swing.JMenuItem menuPMV;
    private javax.swing.JMenuItem menuPendente;
    private javax.swing.JMenuItem menuPesquisaPdt;
    private javax.swing.JMenuItem menuRegVenda;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenu mnu;
    private javax.swing.JDesktopPane panelTelaPrincipal;
    private javax.swing.JTextField txtCaixa;
    // End of variables declaration//GEN-END:variables

    private void setDisplayMode(DisplayMode displayMode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void sleep(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class device {

        public device() {
        }
    }
}
